### ISSUE TITLE
Suggestion: Notification Sound

### ISSUE THREAD

**Issue by s4relok** [hippogamesunity/SimpleAndroidNotificationsPublic#1]
Не хватает возможности установить свой звук для оповещения. 

Это можно сделать в Android плагине, например, вот так:

```
Uri uri = Uri.parse("android.resource://" + context.getPackageName() + "/raw/" + soundName); 
builder.setSound(uri);
```

soundName - параметр, название файла звука
Сам файл звука нужно будет положить в Plugins/Android/raw или в .aar

**Comment by hippogamesunity** [comment]
Обновление 1.9 на ревью, будет доступно через 2-3 дня. Большая просьба закрыть рабочий элемент, если все заработает как нужно =)

**Comment by hippogamesunity** [comment]
https://www.assetstore.unity3d.com/#!/content/71294
