### ISSUE TITLE
Crash: JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xf0

### ISSUE THREAD

**Issue by yanmasharski** [hippogamesunity/SimpleAndroidNotificationsPublic#10]
02-02 11:46:22.068 10693-10709/? A/art: sart/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xf0
02-02 11:46:22.068 10693-10709/? A/art: sart/runtime/check_jni.cc:65]     string: ' 🏆 Emoji bug'
02-02 11:46:22.068 10693-10709/? A/art: sart/runtime/check_jni.cc:65]     in call to NewStringUTF
02-02 11:46:22.068 10693-10709/? A/art: sart/runtime/check_jni.cc:65]     from boolean com.unity3d.player.UnityPlayer.nativeRender()

https://github.com/sqlcipher/android-database-sqlcipher/issues/199 - apparently emoji are not supported for Android 5.0.1

STR:
1)Create notification with Emoji symbols on Android 5.0.1

**Comment by hippogamesunity** [comment]
Sorry for the late response. I was able to check this issue on the latest plugin version (1 FEB 2018) and Android 5.1.1. There is no exception, but emoji doesn't displayed correctly.

Data serialization was introduced in the latest update (with base64 encoding), so can you please check this issue again?

**Comment by shlapkoff** [comment]
I also get this error on Samsung S5 OS 5.1.1

A/art: sart/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xf0
A/art: sart/runtime/check_jni.cc:65]     string: '😱Come back and get 100 coins 🤑bonus!️'
A/art: sart/runtime/check_jni.cc:65]     in call to NewStringUTF
A/art: sart/runtime/check_jni.cc:65]     from boolean com.unity3d.player.UnityPlayer.nativePause()
A/art: sart/runtime/check_jni.cc:65] "UnityMain" prio=5 tid=11 Runnable
A/art: sart/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x12c97e40 self=0xb4833000
A/art: sart/runtime/check_jni.cc:65]   | sysTid=12288 nice=0 cgrp=apps sched=0/0 handle=0xb4905580
A/art: sart/runtime/check_jni.cc:65]   | state=R schedstat=( 20209959780 9007619579 106925 ) utm=1598 stm=422 core=3 HZ=100
A/art: sart/runtime/check_jni.cc:65]   | stack=0xb33c3000-0xb33c5000 stackSize=1036KB
A/art: sart/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
A/art: sart/runtime/check_jni.cc:65]   native: #00 pc 000047e0  /system/lib/libbacktrace_libc++.so (_ZN13UnwindCurrent6UnwindEjP8ucontext+23)
A/art: sart/runtime/check_jni.cc:65]   native: #01 pc 00002ff9  /system/lib/libbacktrace_libc++.so (_ZN9Backtrace6UnwindEjP8ucontext+8)
A/art: sart/runtime/check_jni.cc:65]   native: #02 pc 002524b9  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiPKcPNS_6mirror9ArtMethodE+68)
A/art: sart/runtime/check_jni.cc:65]   native: #03 pc 00235dc9  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+144)
A/art: sart/runtime/check_jni.cc:65]   native: #04 pc 000b327b  /system/lib/libart.so (_ZN3artL8JniAbortEPKcS1_+582)
A/art: sart/runtime/check_jni.cc:65]   native: #05 pc 000b39b1  /system/lib/libart.so (_ZN3art9JniAbortFEPKcS1_z+60)
A/art: sart/runtime/check_jni.cc:65]   native: #06 pc 000b5e47  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckEbPKcz.constprop.129+882)
A/art: sart/runtime/check_jni.cc:65]   native: #07 pc 000be839  /system/lib/libart.so (_ZN3art8CheckJNI12NewStringUTFEP7_JNIEnvPKc+36)
A/art: sart/runtime/check_jni.cc:65]   native: #08 pc 00ffaaa8  /data/app/our.bundle.id/lib/arm/libunity.so (???)
A/art: sart/runtime/check_jni.cc:65]   native: #09 pc 0000809c   (???)
A/art: sart/runtime/check_jni.cc:65]   at com.unity3d.player.UnityPlayer.nativePause(Native method)
A/art: sart/runtime/check_jni.cc:65]   at com.unity3d.player.UnityPlayer.l(unavailable:-1)
A/art: sart/runtime/check_jni.cc:65]   at com.unity3d.player.UnityPlayer$20.run(unavailable:-1)
A/art: sart/runtime/check_jni.cc:65]   at com.unity3d.player.UnityPlayer.executeGLThreadJobs(unavailable:-1)
A/art: sart/runtime/check_jni.cc:65]   at com.unity3d.player.UnityPlayer$c$1.handleMessage(unavailable:-1)
A/art: sart/runtime/check_jni.cc:65]   at android.os.Handler.dispatchMessage(Handler.java:98)
A/art: sart/runtime/check_jni.cc:65]   at android.os.Looper.loop(Looper.java:145)
A/art: sart/runtime/check_jni.cc:65]   at com.unity3d.player.UnityPlayer$c.run(unavailable:-1)

**Comment by hippogamesunity** [comment]
@shlapkoff Do you use the latest plugin version 2.2?

**Comment by shlapkoff** [comment]
I used custom solution for localize text assets in game. All text is stored in XML format.
I found this topic (https://issuetracker.google.com/issues/36988120). This problem is not related to this plugin.

Fix for me: I disabled Emoji when the Android LEVEL API < 23 (Android 6)

**Comment by hippogamesunity** [comment]
@shlapkoff thanks for reply! Yes, I suppose a developer should take care of escaping or removing special chars.
