### ISSUE TITLE
Parameter CustomSound doesn't work on Android 8 (Unity2017.3)

### ISSUE THREAD

**Issue by LexPanin** [hippogamesunity/SimpleAndroidNotificationsPublic#11]
I created raw directory and put into it wav or mp3 file (no uppercase in name).
I set parameter CustomSound = myFileName (without extension)

ER - have notification with custom sound
AR - have notification with default sound

**Comment by hippogamesunity** [comment]
Will check. Maybe build process in Unity 2017 is different to Unity 5.

**Comment by ghost** [comment]
I am facing the same problem now.
In the new environment, custom sound will not play again.

Unity 2017.3.1 f 1
Android 8.0

**Comment by hippogamesunity** [comment]
Will check it as soon as possible, please wait a little bit =)

**Comment by ghost** [comment]
How is the bug fix progressing?

**Comment by hippogamesunity** [comment]
Hi! Just checked it with Unity 2017.3 and Android 7 - it works fine.
Could you confirm that it works with Android 7 and doesn't work with Android 8? Maybe that is the reason?
I will try to get Android 8 device or emulation soon.

**Comment by ghost** [comment]
It will work on Android 7.
Custom notification is not done on Android 8.

**Comment by hippogamesunity** [comment]
Unable to run emulator on my AMD processor that doesn't have VT feature. But I've found this issue:
https://stackoverflow.com/questions/46268684/android-8-notifications-setsound-not-working

Could you please try suggested fix? If this issue relates to sampling rate, I will update plugin manual.

**Comment by ghost** [comment]
I checked the sound data, but there was no problem with the sampling rate.

**Comment by hippogamesunity** [comment]
Sorry for so late response, was waiting for a new Android 8 phone.
Got a progress with this issue. Version 2.4 is already on review.

**Comment by hippogamesunity** [comment]
Hi! Can you confirm thant it works now?
