### ISSUE TITLE
[Question] Is the notification service able to schedule a notification that is meant to be fired after the application is closed?

### ISSUE THREAD

**Issue by EdwinChua** [hippogamesunity/SimpleAndroidNotificationsPublic#14]
First, thanks for your work. It works great for in app notifications when the app is running!

I am trying to implement notifications that fire at certain times after the user has quit the application. I have the following code, which does not work. Is it a limitation of the library? Or will the pro version provide the functionality?

```Csharp
    private void OnApplicationQuit()
    {
        Save();
        NotificationManager.Send(new TimeSpan(0, 0, 10), "Test Title", "Test Message", new Color(255, 0, 0, 1), NotificationIcon.Message);
    }
```

Thanks for your time :)

**Comment by EdwinChua** [comment]
It seems like `OnApplicationQuit()` isn't the right place for the notification manager. Placing the same function call in the `Start()` method works even after the application is closed.

Again, thank you!

**Comment by hippogamesunity** [comment]
Hi! Use OnPause(bool pause) for this purpose!

**Comment by EdwinChua** [comment]
Thank you! works beautifully :)
