### ISSUE TITLE
There is a problem with custom sound

### ISSUE THREAD

**Issue by ghost** [hippogamesunity/SimpleAndroidNotificationsPublic#15]
Even if you enter mp3 or wav file in the raw folder of "simple-android-notifications.aar" and specify the file name, the sound does not sound.

Also, are not the following sentences in the manual a mistake?

simple-android-notifications.aar/res/aar/ding.mp3.
↓
simple-android-notifications.aar/res/raw/ding.mp3.

My environment
AndroidOS 7.0.0
Mac（10.13.3）
Unity2017.1.0f3 & Unity5.6.5f1

**Comment by hippogamesunity** [comment]
Hi! Are you on Windows?

2018-03-24 5:09 GMT+03:00 漁一吉 <notifications@github.com>:

**Comment by ghost** [comment]
I'm sorry. That problem was solved.
However, I have not succeeded in playing custom sounds yet.

**Comment by hippogamesunity** [comment]
Did you check a manual?

2018-03-24 11:57 GMT+03:00 漁一吉 <notifications@github.com>:

**Comment by hippogamesunity** [comment]
It can be this issue: https://github.com/hippogamesunity/SimpleAndroidNotificationsPublic/issues/11
I'll check it soon.

**Comment by ghost** [comment]
It was caused by setting the ring tone and notification sound to 0.
There is no excuse.
The problem was solved.

However, I am glad that there is a function to forcibly change the volume.

**Comment by hippogamesunity** [comment]
How did you set notification volume? I suppose it depends on your system
volume setting.

2018-03-24 12:58 GMT+03:00 漁一吉 <notifications@github.com>:

**Comment by ghost** [comment]
The volume was changed from the terminal button.

Also, I found a wonderful discovery!
By placing mp3 / wav data in Plugins / Android / res / raw folder on Unity, we could play custom sound without changing aar file.

**Comment by hippogamesunity** [comment]
You should get a warning from Unity that this behaviour is obsolete and is
not supported anymore. Recommended resources location is AAR archive.

2018-03-24 13:45 GMT+03:00 漁一吉 <notifications@github.com>:

**Comment by ghost** [comment]
We understand.
I am very grateful to you.

**Comment by hippogamesunity** [comment]
Would be nice to get you rate on Asset Store!
