### ISSUE TITLE
Simple Android Notification - callback on the app sleep state

### ISSUE THREAD

**Issue by shlapkoff** [hippogamesunity/SimpleAndroidNotificationsPublic#16]
Hi, thanks for really good plugin.

I see in documentation:
**"Receiving callback will not work if your app was sleeping. It will only work if app was opened (not resumed) by clicking notification!"**

What is the reason for this?
Maybe there is some way to get a callback in sleep app?
I want to add a reward to users when opening an application from notification. But it's bad user experience if users get reward only if the app closed.

**Comment by hippogamesunity** [comment]
Hi! It seems that this issue does no longer exist. You even don't need to update the plugin.
You can check notification callback when app resumed:
![image](https://user-images.githubusercontent.com/7318172/40242777-32267fda-5ac7-11e8-86d2-77f1c0e235da.png)

**Comment by shlapkoff** [comment]
Thanks, it's really works!
