### ISSUE TITLE
Notifications are not opening the app when using gradle

### ISSUE THREAD

**Issue by StewPerry** [hippogamesunity/SimpleAndroidNotificationsPublic#18]
Hi,

I have imported simple android notification (paid) into our application. It works great except that the notifications do not open our app.

I am running Unity 2017.2.2f1.

I have tried starting a new project with your demo scene. If I don’t use gradle then the notifications DO open the app. If I use gradle then the notifications DO NOT open the app. This is the case for when I use a proguard-user file or not.

I have looked at your troubleshooting page and have checked we are using UnityPlayerActivity, which we are.

Inside the proguard-user.txt file I have added:
-keep class com.hippogames.simpleandroidnotifications.* { *; }

Any suggestions would be greatly appreciated.

Thanks
Stewart

**Comment by hippogamesunity** [comment]
Hi! What is your Android version? Does it happen on all android versions?

**Comment by StewPerry** [comment]
in unity the minimum is set to Android 4.1 Jelly Bean (API level 16)
the maximum is set to automatic (highest installed)

I have tried this on multiple android devices (old to new) and they all behave the same

**Comment by hippogamesunity** [comment]
Just checked this issue, can't reproduce. Did you check this from our FAQ? >
Your app does not launch on clicking the notification?
Seems that you need to check Unity activity name in your app manifest (Plugins/Android/AndroidManifest.xml). It must be UnityPlayerActivity. If you define another activity name (i.e. UnityPlayerNativeActivity that is obsolete), you must change this constant from NotificationManager:

**Comment by Nightloss** [comment]
I have same Issue in paid version. I can send you my grabble build. Just write me in skype - iermakovmykyta

**Comment by StewPerry** [comment]
@hippogamesunity could you send me your test unity project? I can not get this to work. My manifest for the TestProject is:

`<?xml version="1.0" encoding="utf-8"?>`
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"` `xmlns:tools="http://schemas.android.com/tools" package="com.unity3d.player"` `android:installLocation="preferExternal" android:versionCode="1" android:versionName="1.0">`
  `<supports-screens android:smallScreens="true" android:normalScreens="true"' android:largeScreens="true" android:xlargeScreens="true" android:anyDensity="true" />`
  `<application android:theme="@android:style/Theme.NoTitleBar.Fullscreen" android:icon="@drawable/app_icon" android:label="@string/app_name">`
    `<activity android:name="com.unity3d.player.UnityPlayerActivity" android:label="@string/app_name">`
      `<intent-filter>`
       `<action android:name="android.intent.action.MAIN" />`
        `<category android:name="android.intent.category.LAUNCHER" />`
      `</intent-filter>`
      `<meta-data android:name="unityplayer.UnityActivity" android:value="true" />`
    `</activity>`
 `</application>`
`</manifest>`


Plus in the NotificationManager I do have:

> public const string MainActivityClassName = "com.unity3d.player.UnityPlayerActivity";


Is there anything wrong with this?

**Comment by hippogamesunity** [comment]
@Nightloss, @StewPerry Hi! Please upload your test projects where this issue can be reproduced. On Google Drive, for example.

**Comment by StewPerry** [comment]
https://drive.google.com/open?id=1R1hHgJsLowumCi_o_mX_TyieiL9TjYBZ

Thanks

**Comment by StewPerry** [comment]
Hi, have you had a chance to look into this test project I sent?

**Comment by hippogamesunity** [comment]
Hi! Gonna check this on this week.

**Comment by songhojung** [comment]
@StewPerry 
 i saw Simple Android Notifications manual 
there is description 12. requirment.
you try to contain permission and reciever in your menifest.xml

i tried like below this and working!

```
> <?xml version="1.0" encoding="utf-8"?>
> <manifest
>     xmlns:android="http://schemas.android.com/apk/res/android"
>    package="com.unity3d.player">
>   <uses-permission android:name="android.permission.VIBRATE" />
>   <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
>   <application
>   android:icon="@drawable/app_icon"
>       android:label="@string/app_name"
>       android:debuggable="true">
>     <activity android:name="com.unity3d.player.UnityPlayerActivity"
>                 android:label="@string/app_name">
>       <intent-filter>
>         <action android:name="android.intent.action.MAIN" />
>         <category android:name="android.intent.category.LAUNCHER" />
>         <category android:name="android.intent.category.LEANBACK_LAUNCHER" />
>       </intent-filter>
>       <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
>       <receiver android:name="com.hippogames.simpleandroidnotifications.Controller" />
>       <receiver android:name="com.hippogames.simpleandroidnotifications.RebootManager" >
>         <intent-filter>
>           <action android:name="android.intent.action.BOOT_COMPLETED" />
>         </intent-filter>
>       </receiver>
>     </activity>
>   </application>
> </manifest>
```

**Comment by ki4chan** [comment]
@songhojung Hey buddy how did you modify the AndroidManifest.xml file?
I tried extracting simple-android-notifications.aar then making changes in AndroidManifest.xml file and then converting it back to .aar but now I am getting this error in Android studio.
1.
C:\Users\user\.android\build-cache\268839f99648af92334659d071563e10d6563cdf\output\simple-android-notifications\AndroidManifest.xml (The system cannot find the path specified)

**Comment by hippogamesunity** [comment]
Well, I suppose it's setup issue, not the plugin issue.
