### ISSUE TITLE
Android 8.0

### ISSUE THREAD

**Issue by dyfer2004** [hippogamesunity/SimpleAndroidNotificationsPublic#2]
Hi,

Just to let you know,

The plugin works great on Unity 2017.1 & Android 7.1 but nothing is happening when building to a Pixel Phone with Android 8.0.

Great job !

**Comment by hippogamesunity** [comment]
Thanks, I'll check it when Android 8 will be available for me)

**Comment by hippogamesunity** [comment]
Can you confirm that clean setup to empty project doesn't work on API 26? Unfortunately, I've got no real device. But on emulator it works fine, here are my screenshots (API 26+27):
![image](https://user-images.githubusercontent.com/7318172/32504759-a7a3f9da-c3f1-11e7-93dc-6b0b49383209.png)
![image](https://user-images.githubusercontent.com/7318172/32504707-8913c4aa-c3f1-11e7-8fb3-69e2dbc36a86.png)

**Comment by jfbrisebois** [comment]
Tested with clean setup on Nexus 6P (Androit 8.0) with Unity build targeting API 27, I get the following error : 

E/NotificationService: No Channel found for pkg=com.stuff.notificationtest, channelId=null, id=1812932611, tag=null, opPkg=com.stuff.notificationtest, callingUid=10102, userId=0, incomingUserId=0, notificationUid=10102, notification=Notification(channel=null pri=0 contentView=null vibrate=[1000,1000] sound=content://settings/system/notification_sound tick defaults=0x0 flags=0x11 color=0xffff4c26 vis=PRIVATE)

**Comment by hippogamesunity** [comment]
Hi! Can you check the updated plugin please? Everything is fine, on the emulator at least)
https://yadi.sk/d/rK5Lvoqt3PYH4b
Note, that [ChannelId] and [ChannelName] params were added, so you need to update all plugin files.

**Comment by jfbrisebois** [comment]
I tested with the package from the link above and it works.

**Comment by hippogamesunity** [comment]
Hi, yes, the updates are still on review. I think they will be available in
a few days. Thanks for help!
