### ISSUE TITLE
Heads up notification!

### ISSUE THREAD

**Issue by JEOptimal** [hippogamesunity/SimpleAndroidNotificationsPublic#21]
Allow from the plugin to set the priority or always setting it to high. Here is an example of how it should look in the plugin to allow heads up notifications:
`NotificationCompat.Builder mBuilder =
new NotificationCompat.Builder(context).
setSmallIcon(R.drawable.ic_media_play).
setContentTitle("My notification").
setContentText("HelloWorld!").
setDefaults(Notification.DEFAULT_ALL).
setPriority(Notification.PRIORITY_HIGH);
`

This is the key: .setPriority(Notification.PRIORITY_HIGH);

**Comment by hippogamesunity** [comment]
Hi! Will add to next update. By the way, it is set for Stacked Notifications in current version. So it can be a workaround for you now.

**Comment by JEOptimal** [comment]
Thanks! Will try that!

**Comment by hippogamesunity** [comment]
Got a progress with this issue. Version 2.4 is already on review.

**Comment by hippogamesunity** [comment]
Hi! Can you confirm thant it works now?
