### ISSUE TITLE
Unity 2018.2 manifest collides

### ISSUE THREAD

**Issue by sathyaraj-shettigar** [hippogamesunity/SimpleAndroidNotificationsPublic#22]
Try building the latest version with unity 2018.2 and I get the following error. How to solve this?

CommandInvokationFailure: Gradle build failed. 
C:/Program Files/Java/jdk1.8.0_112\bin\java.exe -classpath "C:\Program Files\Unity201802\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-4.2.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx2048m" "assembleRelease"
stderr[
I:\BitBucketRepo\IJS Game UI Framework\UIFramework\Temp\gradleOut\src\main\AndroidManifest.xml:4:113-144 Error:
	Attribute application@icon value=(@mipmap/app_icon) from AndroidManifest.xml:4:113-144
	is also present at [:simple-android-notifications:] AndroidManifest.xml:11:3-36 value=(@drawable/app_icon).
	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:4:3-27:17 to override.
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':processReleaseManifest'.
> Manifest merger failed : Attribute application@icon value=(@mipmap/app_icon) from AndroidManifest.xml:4:113-144
  	is also present at [:simple-android-notifications:] AndroidManifest.xml:11:3-36 value=(@drawable/app_icon).
  	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:4:3-27:17 to override.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 10s
]
stdout[
:preBuild UP-TO-DATE
:GoogleMobileAdsPlugin:preBuild UP-TO-DATE
:GoogleMobileAdsPlugin:preReleaseBuild UP-TO-DATE
:GoogleMobileAdsPlugin:checkReleaseManifest
:GoogleMobileAdsPlugin:processReleaseManifest
:preReleaseBuild
:GoogleMobileAdsPlugin:compileReleaseAidl
:compileReleaseAidl
:GoogleMobileAdsPlugin:packageReleaseRenderscript NO-SOURCE
:compileReleaseRenderscript
:checkReleaseManifest
:generateReleaseBuildConfig
:prepareLintJar
:generateReleaseResValues
:generateReleaseResources
:GoogleMobileAdsPlugin:compileReleaseRenderscript
:GoogleMobileAdsPlugin:generateReleaseResValues
:GoogleMobileAdsPlugin:generateReleaseResources
:GoogleMobileAdsPlugin:packageReleaseResources
:mergeReleaseResources
:createReleaseCompatibleScreenManifests
:processReleaseManifest
See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
:processReleaseManifest FAILED
16 actionable tasks: 16 executed
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1 progress, System.String error)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1 progress)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1 progress)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by hippogamesunity** [comment]
Did you try to remove android:icon from any manifest? From your main manifest or from my asset manifest (inside AAR).

**Comment by sathyaraj-shettigar** [comment]
No. Tried in empty project and got the error

**Comment by hippogamesunity** [comment]
Cool, please attach this empty project to this issues.

**Comment by sathyaraj-shettigar** [comment]
https://www.dropbox.com/s/ee73y5nkh2h6tvh/localNotification.rar?dl=0

**Comment by hippogamesunity** [comment]
Need more time to update Unity. At least I was able to build it with 2018.1

**Comment by sathyaraj-shettigar** [comment]
It works fine in 18.1 Try making a build in 2018.2 with IL2CPP

**Comment by hippogamesunity** [comment]
Simply remove logged attributes from AAR/Manifest to build with Unity 2018.2. I will update the plugin soon.
![image](https://user-images.githubusercontent.com/7318172/43924929-80f5028c-9c2e-11e8-8779-92de529aed3a.png)
