### ISSUE TITLE
LargeIcon not displayed

### ISSUE THREAD

**Issue by NicTda** [hippogamesunity/SimpleAndroidNotificationsPublic#23]
Hi! 
I've got the notifications working (with message / title), tapping on it opens the game fine.
The only issue is that when I use the function SendWithAppIcon() (the one using LargeIcon = "app_icon"), it doesn't actually display the icon (just shows nothing next to the message instead).

I'm *pretty* sure it was showing the default Unity icon when I tested on a blank project...
Anything I'm doing wrong?

Thanks!

**Comment by NicTda** [comment]
After a few tests, it appears that the default Unity icon works fine, but it's not showing up after defining it in the PlayerSettings interface.
I use Unity 2018.1.0 by the way.

**Comment by hippogamesunity** [comment]
Hi! At first, update Unity to 2018.2. Make sure there is no custom
manufacturers' shell on your device. You can also attach demo project so I
could test it.

**Comment by hippogamesunity** [comment]
Fixed in 2.6.
