### ISSUE TITLE
Notification will not show if App is closed or terminated. (Unity 5.6.4p4)

### ISSUE THREAD

**Issue by SorapholB** [hippogamesunity/SimpleAndroidNotificationsPublic#24]
I just tested using the included Demo scene with a clean project. It behaves the same way. If the App is closed or terminated beforehand, notification will not be shown even if it has already been scheduled. This is tested using Unity 5.6.4p4 and Huawei Y6 version2.

**Comment by hippogamesunity** [comment]
Hi! Does you phone have custom UI shell? Also did you check notification settings for the app?

**Comment by SorapholB** [comment]
I am not sure about custom UI shell. However, I did not do anything special with the OS of this phone( its version is Android 6.0). As for notification settings, I have allowed everything for to the Demo App, the problem is most likely not being caused by the notification settings.

**Comment by SorapholB** [comment]
There is one good news; I just tested the Demo App with Galaxy S9, and it seems to be working even when the App has been terminated. I am going to test this on more phone's model.

**Comment by hippogamesunity** [comment]
I've stuck with similar issue on my old phone with custom shell ZUI. Anyway, I will check this issue on my phones available with Unity 5.6 soon.

**Comment by SorapholB** [comment]
I also tested on 2 more phones
- Wiko, Android 6.0.1 => Success
- Oppo, Android 5.1.1 => Fail

It is good to here that you find similar problem on certain phones. If you have any fix or update, please tell me. Thank you.

**Comment by hippogamesunity** [comment]
I've tested on Unity 5.6 and Unity 2018 and have no difference.
It works with Xiaomi Mi 5 (MUI) and doesn't work with Lenovo ZUK (ZUI).
I suppose it can relate to energy saving settings or custom UI shell.
For example, I can find a lot of the same issues on ZUI forums (https://zukfans.eu/community/threads/notifications-problem.407/).

**Comment by SorapholB** [comment]
Is there anyway to determine that the phone is MUI or ZUI? This is going to be a problem if a lot of phones are using ZUI.

**Comment by hippogamesunity** [comment]
ZUI is Lenovo onlu shell.

**Comment by SorapholB** [comment]
That is quite strange. If that is the case, why can the symptom be reproduced on OPPO A37 and Huawei Y6 version2.?

**Comment by hippogamesunity** [comment]
I suppose their shells also have some kind of energy saving mode. Here is what I've found about Huawei: https://www.forbes.com/sites/bensin/2016/07/04/push-notifications-not-coming-through-to-your-huawei-phone-heres-how-to-fix-it/#1004c1511ccc

**Comment by hippogamesunity** [comment]
"This is partly due to EMUI's very aggressive battery saving methods, which forbid apps from running in the background when the phone's screen is off. It's also partly due to the phone somehow thinking notifications aren't worthy to take up real estate on your pull-down shade unless you've marked the app "priority.""

**Comment by SorapholB** [comment]
After I set the Demo App to be protected on Huawei, the notification is triggered after the App is terminated now. Thank you very much for your help and contribution. This really helps.
