### ISSUE TITLE
Unity 2018.2.5f1 (Game icon not show)

### ISSUE THREAD

**Issue by Vah94** [hippogamesunity/SimpleAndroidNotificationsPublic#25]
On Unity 2017.4.8 Game icon show on notification, but not on last Unity

**Comment by hippogamesunity** [comment]
Hi! Do you sure it relates to Unity version not a specific device or Android version?

**Comment by Vah94** [comment]
Yes... I thin something work diferent on 2018 Unity
![image](https://user-images.githubusercontent.com/42799443/45034955-e2ec6d00-b069-11e8-8b96-924ca6a8285d.png)

**Comment by Vah94** [comment]
There are 3 space for Icon image, maybe your plugin cant get path of image?

**Comment by hippogamesunity** [comment]
It may relate to Adaptive Icons
https://forum.unity.com/threads/android-oreo-icon-is-incorrect-on-unity-5-5-0p4.492300/
As I see, there are Background + Foreground icons now, and Unity doesn't contain "app_icon" inside the resources folder anymore. You could use small icon till I will find any resolution for this issue.

**Comment by Vah94** [comment]
ok. I will wait :)

**Comment by hippogamesunity** [comment]
As a workaround I you can use custom small icons. I will request the info about app icon from Unity.

**Comment by zenith-jacob** [comment]
Hey, can't you just add another parameter, for CustomLargeIcon so we can set the large icon here, just like small icons?

**Comment by hippogamesunity** [comment]
It's very fragile workaround, by it works on my device with Android 8.
https://stackoverflow.com/questions/44447056/convert-adaptiveicondrawable-to-bitmap-in-android-o-preview/46018816#46018816

**Comment by hippogamesunity** [comment]
Fixed in 2.6.
