### ISSUE TITLE
Sound can´t get switched off

### ISSUE THREAD

**Issue by The-Arrival** [hippogamesunity/SimpleAndroidNotificationsPublic#26]
I´m Scheduling a repeated notification, for test purposes at a specific time, repeatSpan is 30 seconds.
The Notification can be with or without a custom sound, based on user settings

Issue: Once the notification is scheduled with a sound, it will ever play with a sound, even if scheduled without... and vise versa.

Example Project can be found here: https://drive.google.com/open?id=1hrPxUm0akyRQqrwQpKlcf4kKOPSWWm7c

**Comment by hippogamesunity** [comment]
Hi! It would take a less time if you provide a working example. Seems you even didn't test it before uploading. NotificationHandler and Example are missed in SampleScene.

Anyway, here are my comments:
- use NotificationManager.CancelAll for cancelling notifications
- don't use NotificationIdHandler.AddScheduledNotificaion(id) as it's called inside NotificationManager.SendCustom
- as described in Manual.pdf (13.2 ADDING CUSTOM SOUNDS)

> Notes: in Android API 26 (Oreo) notification sounds are moved to channels. After a new channel is
> created, it will be displayed in the app’s notification settings. All channel settings (including custom
> sound) should be defined while creating a new channel. There is no way to change channel’s settings
> (including custom sound), except reinstalling the app.

This means that Android saves notification params and only user can change them later from Settings/Apps. You can read about this behaviour here: https://developer.android.com/training/notify-user/channels
![image](https://user-images.githubusercontent.com/7318172/45295923-fafc3a80-b508-11e8-8eab-d39fed2c5832.png)

**Comment by The-Arrival** [comment]
Hello,

first of all, thank you for our answer and your support. The missing stuff was NOT due to me not caring, but to having basically zero time to build an example project for you between my other tasks... i did it anyway and i just forgot to **save the Scene** before zipping and uploading it.

So sorry for the inconvenience.

In any case you already pointed me to the right direction that with O notification settings can´t get changed by the application anymore. I overlooked that section in the manual.

**Comment by hippogamesunity** [comment]
Ok, good luck!
