### ISSUE TITLE
Tap notification icon won't return app

### ISSUE THREAD

**Issue by samliu319** [hippogamesunity/SimpleAndroidNotificationsPublic#27]
Because my main activity is "com.google.firebase.MessagingUnityPlayerActivity" not "com.unity3d.player.UnityPlayerActivity", so it can't handle local notification message correctly. Could you write a addition activity class to handle local notification message independent that it won't affected by main activity? Thank you.

**Comment by hippogamesunity** [comment]
https://github.com/hippogamesunity/SimpleAndroidNotificationsPublic/wiki/Troubleshooting
