### ISSUE TITLE
CustomData, Cancel and Pending

### ISSUE THREAD

**Issue by ghost** [hippogamesunity/SimpleAndroidNotificationsPublic#28]
Hello,
unfortunately I can't find a description of the whole functionality of your plugin. I need the following functionality for my application: 
```
public struct LocalNotification {
	public string id;
	public string title;
	public string body;
	public DateTime time;
	public string customData; //<--- especially this one
}

public interface ILocalNotificationService {
	void Register();
	LocalNotification[] GetAllCurrent();
	bool Pending(string id, out LocalNotification localNotification);
	void Clear(string id);
	void ClearAll();
	void Schedule(LocalNotification notification);
}
```
Is it possible with the plugin to find out if a local notification with an id is currently pending? And delete it with an id if necessary? Furthermore it is possible to add custom user data like in the implementation of Unity for iOS? Thanks a lot!

**Comment by hippogamesunity** [comment]
Hi! You can use NotificationIdHandler for managing IDs. It's not possible to implement custom data on iOS.

**Comment by ghost** [comment]
But that statement is not correct. As I mentioned before, Unity has customData for local notifications in its iOS implementation. See here the field userInfo: https://docs.unity3d.com/ScriptReference/iOS.LocalNotification.html

Furthermore you can see in the iOS documentation that there is a userInfo in the payload of the notification which is intended for customData, see here: https://developer.apple.com/documentation/usernotifications/unnotificationcontent/1649869-userinfo

**Comment by hippogamesunity** [comment]
Hi! Did you notice that this asset is for Android only?) You can edit iOS code to fit your needs =) And you can refer to Unity docs for more details.

**Comment by ghost** [comment]
Yes, of course. I just wanted to answer your answer. Maybe it was just a typo that you wrote iOS?
In any case customData is also possible in Android if your answer was aimed for Android instead of iOS See here under putExtra: https://developer.android.com/reference/android/content/Intent.
