### ISSUE TITLE
having problem when Exporting my Unity project in andriod studio

### ISSUE THREAD

**Issue by ki4chan** [hippogamesunity/SimpleAndroidNotificationsPublic#30]
![screenshot 35](https://user-images.githubusercontent.com/30446691/47111517-5d1b2e80-d271-11e8-8dd1-775cf9c937c6.png)

Its a game made with unity, just to enable muiltiDex I have to export my project in Adroid studio.

**Comment by hippogamesunity** [comment]
Need to make additional research in the future. I don't use and don't have Android Studio right now.
