### ISSUE TITLE
Notification fired from the plugin does not have a time stamp on Galaxy S9

### ISSUE THREAD

**Issue by SorapholB** [hippogamesunity/SimpleAndroidNotificationsPublic#31]
On Galaxy S9 (Android 8.0), notification fired from the plugin does not have a time stamp. However, notifications from other apps do have it. 

Look at an example picture below, notification from an email is shown with a time stamp but notification of Cricket Tycoon(my app) is displayed without it.

I have looked in to the notification settings of my app. Every option has already been turned on and allowed. (no topic related to the time stamp though...)

There seems to be no parameter associated with the appearance of a time stamp in the plugin. 
Thus, Please investigate this issue.

PS. When the notification is fired in OPPO (Android 5.0), it appears with a time stamp. I heard that after Android 7.0, the time stamp is not a default setting anymore. If you want to fire the notification with a time stamp, you need to call a specific method for it to appear.

![image](https://user-images.githubusercontent.com/42437879/47563559-587b0800-d94c-11e8-8129-8b152295e379.png)

**Comment by hippogamesunity** [comment]
Will be fixed in next update, thanks!
https://developer.android.com/reference/android/app/Notification.Builder#setShowWhen(boolean)

**Comment by hippogamesunity** [comment]
Fixed in 2.6.
