### ISSUE TITLE
Notification not show

### ISSUE THREAD

**Issue by javis007** [hippogamesunity/SimpleAndroidNotificationsPublic#32]
Hi 
hi, I test the demo on my android mobile nexus 6P  7.1.1,
the notification only sound come out, but i can't see the notification push.
when i drop down the top notification bar,  then i can see the notification at list.
How the notification sound and view come out at the same time?
Is there something wrong i miss?
Thank you.
![321b31f101398b21572456e84e189de8](https://user-images.githubusercontent.com/6762181/47827960-b5971380-ddbb-11e8-828e-34828abb2de8.jpg)

**Comment by hippogamesunity** [comment]
There is notification and sound, so it was scheduled and fired correctly.
It may an an issue with your phone's UI. Did you try it on another device?

**Comment by bigmistqke** [comment]
Same happening over here with my Moto G6 and Android 8 in a fresh project with the sample-project: 
notification does show in list and it makes a sound when it enters, but it doesn't 'pop up' at the top. 
Notifications from other apps do pop up at the top.

**Comment by hippogamesunity** [comment]
Hi! Can you make 2 screenshots - with correct and wrong notifications displayed?
