### ISSUE TITLE
Plugin works good on Android 7 and below but not works on Android 8.

### ISSUE THREAD

**Issue by vgery16** [hippogamesunity/SimpleAndroidNotificationsPublic#37]
This Plugin worked on :
--------------------------------
Device: Samsung Galaxy J5
Version: Android 6.0.1 

Device: Samsung Galaxy SM-A510F
Version: Android 7.0

It looks Plugin works good on Android 7 and below.

This Plugin don't worked on:
--------------------------------------------
Device: Samsung Galaxy S8+
Version: Android 8.0.0

No Notification appeard, no sound, no vibration, nothing.
How can I fixe that ? 

My Setup: 
----------------------------
I have last version of Simple Android Notifications Free.
Unity 2017.3.1f1 with Android SDK 26.0
Other Plugins with Manifests: 
- Facebook, 
- GoogleMobileAds

**Comment by hippogamesunity** [comment]
Hi! Please attach the screenshot of system notification settings for the app.

**Comment by vgery16** [comment]
Hi, Thank you for fast answer!
----------------------------
Where can I find the System notification settings ? Which part of Unity or what part of code is that ?

**Comment by hippogamesunity** [comment]
Hi. Open System settings of your phone. Usually Application/Notification
settings.

**Comment by vgery16** [comment]
![image](https://user-images.githubusercontent.com/11043529/48901958-56c33800-ee57-11e8-99dc-6923b339bbfa.png)

"Értesítések Engedélyezve"
As you can see Notifications = Enabled (true)

**Comment by hippogamesunity** [comment]
Hi! The first thing I would check is testing on another Android 8 device. You have custom shell, this may cause the issue.

I can confirm, that:
- the latest plugin version works with clean Android 8 for other users
- you have no manifest issues if it works on Android 7

Also you should check your phone's logs (using adb logcat), this may be related to this issue: https://github.com/hippogamesunity/SimpleAndroidNotificationsPublic/issues/34

**Comment by vgery16** [comment]
On Samsung Galaxy S8+every other apps notification works fine except this one.

Do you have any other idea how can I fix that ? (I cannot use adb logcat on that phone because its not rooted)

This Plugin worked on
-----------------------------
HUAWEI FIG LX1 (Android 8.0)

**Comment by hippogamesunity** [comment]
I'm still trying to find the device from my friends...

**Comment by anilraj0410** [comment]
Hi,
I had an issue with this plugin in vivo mobile after android 8 version notification not shows when I was given auto start enabled its working without that any option for that please help me in paid version.
