### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by ItsAntiUp** [hippogamesunity/SimpleAndroidNotificationsPublic#39]
Hello. I've been using a free version of this plugin for like a year now and I can truly say it is fantastic. Today I bought the full version for extra functions and I have some questions about it.

When I set a notification, for example, to come after 2 minutes, everything works as expected, but if I reboot my device, notification comes after 4 or 5 minutes. What could be the cause of this?

If I receive a notification and I click on it, nothing happens. Is there a way to make notification open my application (when clicked)?

Is there a way I could change the LED light color in the device for my notifications? (Now it shows green only)

Thanks in advance for any help.

**Comment by hippogamesunity** [comment]
Hi! Thanks!
About you issue - you need second tip from https://github.com/hippogamesunity/SimpleAndroidNotificationsPublic/wiki/Troubleshooting

NotificationParams.LightColor is the light color. Not all phones support it and even have the color light.

**Comment by ItsAntiUp** [comment]
Hi. Thanks for the response. I figured everything out, but there's still one problem. If I set 2 notifications to come at the same time, they both come as expected but the alarm plays not 2 but 3 times. If I set 3 notifications, 4 sounds play, and so on... Is there any problem regarding the plugin or maybe I did something wrong? Thanks for any help.

**Comment by hippogamesunity** [comment]
...and about restarting the device - after the reboot all notifications are inexact.
About sound issue - please create a bug as another issue.
