### ISSUE TITLE
Notification do not appear after closing the app with other plugins.

### ISSUE THREAD

**Issue by aqrel** [hippogamesunity/SimpleAndroidNotificationsPublic#4]
Plugin run well with android 8.0 and unity 2017.1 when i try it alone.

But if integrate with GoogleMobileAds or GooglePlayGames the notifications do not appear after closing the application.

Those other plugins adds androidManifest.xml i'll try to add activity as u mean in Manual but nothing happen.

Surely I'm misreading the AndroidManifest.

Can u write an example please.

**Comment by hippogamesunity** [comment]
Hi! The plugin has its own manifest inside .ANR. Did you check main
activity name?
Also there was report that it doesnt work with android 8, but I cant
confirm this yet.

**Comment by copid** [comment]
when app closed,it still work? how?

**Comment by hippogamesunity** [comment]
No, it doesn't. All notifications are sheduled with Android AlarmManager.

**Comment by hippogamesunity** [comment]
Can you confirm that clean setup to empty project doesn't work on API 26? Unfortunately, I've got no real device. But on emulator it works fine, here are my screenshots (API 26+27):
![image](https://user-images.githubusercontent.com/7318172/32504759-a7a3f9da-c3f1-11e7-93dc-6b0b49383209.png)
![image](https://user-images.githubusercontent.com/7318172/32504707-8913c4aa-c3f1-11e7-8fb3-69e2dbc36a86.png)
