### ISSUE TITLE
Notifications at the same time

### ISSUE THREAD

**Issue by ItsAntiUp** [hippogamesunity/SimpleAndroidNotificationsPublic#40]
There is a strange bug going on where if I set for example 2 notifications to come exactly at the same time, they arrive as expected but 3 notification sound play. If I set 3 simultaneous notifications, 4 sounds play and so on..

**Comment by hippogamesunity** [comment]
When I make 2 ScheduleNormal calls I get 2 beeps, but when I make 2 ScheduleGrouped calls I get 3 beeps. I suppose it's because notification group is fired with sound as well. Is this your use case?

**Comment by hippogamesunity** [comment]
Looks like it was caused by https://developer.android.com/reference/android/app/Notification.Builder#setGroupAlertBehavior(int)

If I set GROUP_ALERT_CHILDREN, then there is no group sound. Just wait for the asset update!

**Comment by ItsAntiUp** [comment]
Yes I used grouped notifications when this happened. Thanks.

**Comment by hippogamesunity** [comment]
2.7 update was is available.
