### ISSUE TITLE
Notifications not being shown after reboot

### ISSUE THREAD

**Issue by erpresi** [hippogamesunity/SimpleAndroidNotificationsPublic#43]
Hello, I'm using the last version of the plugin (2.7) in Unity 2018.2.16 with an Redmi Note 5 with OS MIUI 10.0 Global that is the UI over an Android 8.1.

The problem that I'm facing is that when I set the notification to fire (after, let's say 5 minutes) and I do not switch off the mobile then it works (even if I remove the app from the background), but if I switch off the mobile and I turn it on before the given delay then I never get the notification.

As a side note I have two more questions (both related to channels since by default the sounds and lock screen notifications are disabled):
-How can I use the system default notification sound?
-How can I display the notification in the lock screen (for example If I get an email, I'm able to see the notification in the lock screen and in the notification area, now my app is only displaying notifications in the display area)?

Thanks.

**Comment by madratzz** [comment]
I am also facing the same issue. 
Unity Version: 2018.3.2f1
Plugin Version: 2.8
Android Version: 8.0
Device: Samsung Galaxy S8+

**Comment by hippogamesunity** [comment]
I will check it in a few days.

**Comment by marnelle1** [comment]
> 
> 
> I will check it in a few days.

Hey! Any news? :)

**Comment by alexanderbergerhd** [comment]
I'm also having the same issue! Please fix it!
