### ISSUE TITLE
Working Around Adaptive Icons

### ISSUE THREAD

**Issue by charlie-sbg** [hippogamesunity/SimpleAndroidNotificationsPublic#45]
Hello.  For us to get Adaptive Icons to show well on Android 9.0 (building to sdk 28), we needed to change the icon value in our AndroidManifest from android:icon="@drawable/app_icon" to "@mipmap/ic_launcher".

This caused SimpleAndroidNotification to show an error during build because it wants to use the old value.  If we override SimpleAndroidNotification and force the use of our new icon name, we get correct Android 9.0 Adaptive Icons on the home screen, however now the notifications show an icon of a red box.

Is there a solution to this?
Thanks!

**Comment by hippogamesunity** [comment]
Hi! Please create and attach a small demo project with your setup where this problem can be reproduced.
Meantime I can confirm that "drawable" is "hardcoded" inside java code.

**Comment by charlie-sbg** [comment]
Thanks for the reply.  I can't make a small build today but I can show the result and have pasted a screenshot of the notification being a red box.  We are wondering if this may be an issue with Android 9.0 in general.  Not just with adaptive icons requiring us to change the icon reference.  Will get back with more tomorrow.  But maybe this helps to know?!

![redbox](https://user-images.githubusercontent.com/46855600/51501121-7efee280-1d85-11e9-8600-bfe6358f5d3b.png)

**Comment by charlie-sbg** [comment]
We've verified that the red icon appears in Android 9.0 even without attempting adaptive icons.  For the record, this was a custom icon, not a standard one.  It works fine in older Android versions.

**Comment by hippogamesunity** [comment]
Still need to check your project setup. Manifest, packed icon and so on. Please attach a demo project.

**Comment by charlie-sbg** [comment]
Hi.  It looks like we used this tool wrong all year :)  It only became obvious for Android 9.0 (Pi).  We had set a custom "small icon" and did not use the app icon also (see the screenshots above).  By trying to use a multi-color icon for the "small icon" we finally had this issue with Android 9.0.

Sorry!
