### ISSUE TITLE
show Notification but not open game

### ISSUE THREAD

**Issue by thanhtoan88** [hippogamesunity/SimpleAndroidNotificationsPublic#46]
i using on unity 2018.2.17f1.
i click on Notification in my device, but not open my game. please!

**Comment by hippogamesunity** [comment]
https://github.com/hippogamesunity/SimpleAndroidNotificationsPublic/wiki/Troubleshooting

**Comment by thanhtoan88** [comment]
thank  you! :)

**Comment by hippogamesunity** [comment]
Good luck! Hope to see your feedback on the Asset Store!

**Comment by khanhjp1** [comment]
please help me i can't open app! this is my AndroidMainfest!
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools"
          package="${applicationId}"
          android:versionCode="1"
          android:versionName="1.0">
  <uses-permission android:name="android.permission.INTERNET" />
  <application android:label="@string/app_name"
               android:icon="@drawable/app_icon"
               android:usesCleartextTraffic="true">
    <?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools"
          package="${applicationId}"
          android:versionCode="1"
          android:versionName="1.0">

**Comment by khanhjp1** [comment]
<uses-permission android:name="android.permission.INTERNET" />
  <application android:label="@string/app_name"
               android:icon="@drawable/app_icon"
               android:usesCleartextTraffic="true">
    <activity android:name="com.google.firebase.MessagingUnityPlayerActivity"              android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
      <meta-data android:name="unityplayer.UnityPlayerActivity" android:value="true" />
    </activity>
    <service android:name="com.google.firebase.messaging.MessageForwardingService"
             android:exported="false"/>
  </application>
</manifest>

**Comment by khanhjp1** [comment]
![Capture](https://user-images.githubusercontent.com/31516966/57941175-6b5d2600-78f8-11e9-915b-7ceb8745b275.PNG)
this is my AndroidMainfest

**Comment by hippogamesunity** [comment]
Hi! Does demo scene built work with empty project setup?

**Comment by khanhjp1** [comment]
i try with empty project setup everything oke! but i add it to my project, it not work, why?

**Comment by khanhjp1** [comment]
i think AndroidMainfest cause

**Comment by khanhjp1** [comment]
i'm detele AndroidMainfest and it work! thank you very much!

**Comment by hippogamesunity** [comment]
Great! Hope to get your feedback on the Asset Store!

**Comment by khanhjp1** [comment]
i'm review 5 start! Thank you
