### ISSUE TITLE
Cannot turn off notification sound 

### ISSUE THREAD

**Issue by ineooh** [hippogamesunity/SimpleAndroidNotificationsPublic#47]
I use Simple Android Notifications Free.
I set :  Sound = false in notificationParams BUT the sound still on. 
Using Unity 2018.3.0f2  and device Android 8.1.0

**Comment by hippogamesunity** [comment]
https://github.com/hippogamesunity/SimpleAndroidNotificationsPublic/issues/26

**Comment by hippogamesunity** [comment]
Update 2.8 will be available in a few days.
- update the plugin
- delete a notification channel
- create a new channel with new settings
