### ISSUE TITLE
 ClearAll not remove old sheduled notifications

### ISSUE THREAD

**Issue by fudogorg** [hippogamesunity/SimpleAndroidNotificationsPublic#49]
Why method ClearAll not remove old sheduled notifications?
We send the notification with timespan 1 hour, but then we want it to come not in an hour, but timespan 2 hours. How can this be done?

**Comment by hippogamesunity** [comment]
Hi! Make sure you are using the latest version. Then just call NotificationManager.CancelAll()

**Comment by hippogamesunity** [comment]
You can't change notification delay. Remember it's Id (returned by SendCustom), call Cancel(Id) and then schedule a new one.

**Comment by fudogorg** [comment]
I use version 2.7
NotificationManager.Send(3600, ...
after some time I call:
NotificationManager.CancelAll();
NotificationManager.Send(5000, ...
close game and receive first message.

**Comment by fudogorg** [comment]
I try with id too.

**Comment by hippogamesunity** [comment]
Can you reproduce it with smaller delays so I could try it too?
Does CancelAll work with epmty project + clean setup? I mean the demo scene, where all notifications have 5 mins delay. In my case Yes, but developers always say this =)

**Comment by fudogorg** [comment]
Sorry. All works fine.
I made a mistake )

**Comment by hippogamesunity** [comment]
Great, good luck!
