### ISSUE TITLE
How to pass callbacks from Unity?

### ISSUE THREAD

**Issue by studentutu** [hippogamesunity/SimpleAndroidNotificationsPublic#51]
I need to receive callbacks from notifications. in your pdf stated that we should use 

1. refer to example scene, where notification with callback is creating
2. Set NotificationParams.CallbackData when creating notification. It has string type, so you can
store JSON here
3. Call NotificationManager.GetNotificationCallback() in Awake or anywhere else. It will return
notification NotificationCallback, or null if app was launched NOT from the notification

In the free version, there is no NotificationManager.GetNotificationCallback().
but there is a string CallbackData that we should use.
Should I convert the class to json and pass it inside the CallbackData  or what ?

**Comment by hippogamesunity** [comment]
Hi! As the asset description says, it's a feature from the paid version.

**Comment by studentutu** [comment]
@hippogamesunity  I see, thanks
