### ISSUE TITLE
Repeated notification question

### ISSUE THREAD

**Issue by Daahrien** [hippogamesunity/SimpleAndroidNotificationsPublic#52]
>  FAQ "How to schedule repeated notification every day at 18:00 o'clock?
> First you'll need to calculate the delay to the nearest event. Pass this value to NotificationParams.Delay parameter. Then set NotificationParams.Repeat=true and NotificationParams.RepeatInterval=TimeSpan.FromDays(1)

> var targetTime = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 18, 0, 0); if (targetTime < DateTime.Now) targetTime = targetTime.AddDays(1); var timeLeft = targetTime - DateTime.Now;"

If I call this everytime the app is launched, will it multiply the notifications every launch? how to do it so its not multiplied, I hope you understand me :p

**Comment by Lestat** [comment]
actually it doesnt even have a .Repeat option, also .multiline doesnt appear either, thats pro only or?

**Comment by hippogamesunity** [comment]
Hi! Just call CancellAll on app start.
