### ISSUE TITLE
Possible with time?

### ISSUE THREAD

**Issue by PalDiaray** [hippogamesunity/SimpleAndroidNotificationsPublic#55]
Hello,

i have a question about the notification system. Can i enter a date to remind me? For Example, if i want a notification on a specific date, how do i enter this into the c# line?

greetings,
PalDiaray

**Comment by hippogamesunity** [comment]
Hi! Simply calculate a delay to desired date. Delay = target - now.

**Comment by PalDiaray** [comment]
Thanks for your answer!
Have a nice Day

**Comment by PalDiaray** [comment]
> Thanks for your answer!
> Have a nice Day

Sorry, and how i can calculate the Timedifference? 😅 If i want a difference between 5 Days from now in seconds, what do i have to use? Because i cant subtract from integer to datetime.
Thanks,
PalDiaray

**Comment by hippogamesunity** [comment]
You should refer to C# DateTime and TimeSpan classes on MS docs. There are a lot of useful methods like .AddSeconds and so on. Basically, my asset Delay is TimeSpan, which can be obtained like this:

var delay=DateTime.Now.AddDays(5) - DateTime.Now;
var delayInSeconds = delay.TotalSeconds;
