### ISSUE TITLE
Can't get Custom Sound, Lights, and Application Launch from Notification to work.

### ISSUE THREAD

**Issue by Beno7** [hippogamesunity/SimpleAndroidNotificationsPublic#57]
Hi,

I am having troubles with applying custom sounds, and custom lights with the app's notifications using the premium version. Specifically, the notification plays a default notification sound (not the custom sound I have dictated it to use), and the test device's light notification feature does not turn on. Below is my code:

```
var notificationParams = new NotificationParams
{
            Id = NotificationIdHandler.GetNotificationId(),
            Delay = TimeSpan.FromSeconds(30),
            Title = "Sample Notification",
            Message = "Sample Notification",
            Sound = true,
            CustomSound = "pigsnort",
            Vibrate = true,
            Vibration = new[] { 500, 0, 500, 0, 0, 0 },
            Light = true,
            LightOnMs = 1000,
            LightOffMs = 1000,
            LightColor = new Color(250f / 255f, 109f / 255f, 255f / 255f),
            SmallIcon = NotificationIcon.Pig,
            SmallIconColor = new Color(250f / 255f, 109f / 255f, 255f / 255f),
            LargeIcon = "app_icon",
            ExecuteMode = NotificationExecuteMode.Exact,
            Importance = NotificationImportance.Max,
            ChannelId = "com.sampleChannel.app.generalNotifications",
            ChannelName = "GeneralNotifications"
};

NotificationManager.SendCustom(notificationParams);
```

Here is the altered .aar file: 
[Archive.zip](https://github.com/hippogamesunity/SimpleAndroidNotificationsPublic/files/2930170/Archive.zip)

Further, the notification sent via the code above does not seem to open the app once I click on it. Other custom features, e.g., Custom Icon, and the Notification Tint Color, seems to be working perfectly.

**Notes:**
I'm using Samsung Galaxy s9 running on Android Pie (Android 9).

Am I missing something here?

**Comment by hippogamesunity** [comment]
You can't change some notification params like Sound after a channel was created. You should delete a channel or use another channel Id. Also you can manually change Sound from app settings.
About clicking notification issues - check FAQ. If it doesn't help, make sure that it works with clean setup in demo project.

**Comment by Beno7** [comment]
Got it working. To those who suffer the same problem, I suggest you check out the "Troubleshooting" section in this repo's wiki: https://github.com/hippogamesunity/SimpleAndroidNotificationsPublic/wiki/Troubleshooting

**Comment by hippogamesunity** [comment]
Well, that's why it was created) Good luck!
