### ISSUE TITLE
App does not load fully after notification 

### ISSUE THREAD

**Issue by yarkowskii** [hippogamesunity/SimpleAndroidNotificationsPublic#58]
Hi, hippogamesunity!!
I have a situation. So 2-3 first times when i received a notification everything is good(app starts) next time when i received a notification i try to open my app and after Unity logo nothing happens just clear Unity logo's background and no errors in Console(i used Development build for my app). I have found out that the problem in these notifications, but i do not know where exactly.
When app closing i doing next:
1) Cancel all exists notifications
2) Send in specific time
![Screenshot from 2019-03-25 19-13-42](https://user-images.githubusercontent.com/47320570/54939814-2b01ad00-4f32-11e9-804a-afcd7ffff013.png)

**Comment by hippogamesunity** [comment]
Hi! You are talking about Start issue but the code is executed on app Quit? Did you check ADB logs?

**Comment by yarkowskii** [comment]
I have checked ADB logs and there was nothing that could help me

**Comment by yarkowskii** [comment]
Can this problem affected by count of notifications which i called? Or because i cancelled all notifications and then again call them every time
?

**Comment by yarkowskii** [comment]
By the way in your DemoScene everything works fine. App opens every time

**Comment by hippogamesunity** [comment]
It may be call loop for example. You should make more research. No, there is no limit on notifications, except phone's storage.

**Comment by yarkowskii** [comment]
Is it right calling?
![Screenshot from 2019-03-25 22-10-30](https://user-images.githubusercontent.com/47320570/54950966-2eedf900-4f4b-11e9-9557-330f0a324030.png)

And SendDailyNotif function:
![Screenshot from 2019-03-25 22-12-29](https://user-images.githubusercontent.com/47320570/54950948-272e5480-4f4b-11e9-94f1-301e1b8bc006.png)

**Comment by yarkowskii** [comment]
I tried to send 2-3 notifications when i quit the game and without canceling all ones when i opened the game. So i quit the game set my phone's system time to right time when i should receive notification then i open the game. After 6 repeats of this game does not load fully.
Something that i've done is wrong?

**Comment by hippogamesunity** [comment]
Well, please create and upload a demo project where I could reproduce the
issue. The screenshots I see can't make the situation clear for me.

**Comment by yarkowskii** [comment]
I've found a problem. It wasn't a problem with notifications. Your notifications are perfect.
Sorry:)

**Comment by hippogamesunity** [comment]
I've also updated Troubleshooting page, so you can refer to it: https://github.com/hippogamesunity/SimpleAndroidNotificationsPublic/wiki/Troubleshooting
