### ISSUE TITLE
Show notification for a specific time

### ISSUE THREAD

**Issue by ribusja** [hippogamesunity/SimpleAndroidNotificationsPublic#61]
Hello. I'm using paid version of your plugin and i have a question.
I want to close notification automatically after some time after notification was shown, even if application is not launched (give bonus through notifications, but only available for 30 mins. If user ignores this it'll close). Can I do this with your plugin?

**Comment by hippogamesunity** [comment]
Hi! No, you need 3rd party service running to handle this.
