### ISSUE TITLE
java.lang.ClassNotFOundException:com.hippogames.simpleandroidnotifications

### ISSUE THREAD

**Issue by StickmanWarriorsGame** [hippogamesunity/SimpleAndroidNotificationsPublic#62]
when using some features of firebase: "Android.JavaException:java.lang.ClassNotFoundException:com.hiphopgames.simpleandroidnotification". What can I do to solve this problem?Thanks.I using unity 2018.2.6f1 and grade build.

**Comment by hippogamesunity** [comment]
Hi! Did you check FAQ about Proguard flags?

**Comment by hippogamesunity** [comment]
Hope this helped.
I've also updated Troubleshooting page, so you can refer to it: https://github.com/hippogamesunity/SimpleAndroidNotificationsPublic/wiki/Troubleshooting
