### ISSUE TITLE
Repeated notification not working properly on android 9

### ISSUE THREAD

**Issue by mushiirah-etwarooah** [hippogamesunity/SimpleAndroidNotificationsPublic#63]
Tested on Samsung A50 and Pixel 2 with Android 9.

Method:
 public void ScheduleRepeated()
        {
            //Android Local Notification
            var notificationParams = new NotificationParams
            {
                Id = NotificationIdHandler.GetNotificationId(),
                Delay = TimeSpan.FromDays(5),
                Title = "AppName",
                Message = I2.Loc.ScriptLocalization.Get("localNotifMessage", true),
                Sound = true,
                Vibrate = true,
                Light = true,
                LightOnMs = 1000,
                LightOffMs = 1000,
                SmallIcon = NotificationIcon.Bell,
                SmallIconColor = Color.white,
                LargeIcon = "app_icon",
                ExecuteMode = NotificationExecuteMode.Inexact,
                Repeat = true,
                RepeatInterval = TimeSpan.FromDays(1) // Don't use short intervals as repeated notifications are always inexact
            };

            NotificationManager.SendCustom(notificationParams);
        }

The notification appears on the 1st day, the 2nd day and 3rd day but after that no notification at all.

Any help?

**Comment by hippogamesunity** [comment]
Hi! Just got Mi 9 SE with Android 9, so I was able to test it (Unity 2018.4, latest Android SDK). Got it working with 10/30s intervals. I can only note that with ExecuteMode = NotificationExecuteMode.Inexact notifications become more unstable and can be shown with unstable delays (sorry for obsolete comment about inexact mode, repeated notifications can be exact). Also, If you set such short delays like 10/30s, notifications are also shown not preciously (in my case I can see 7 notifications and then they stopped adding before running the app again).

I've also updated Troubleshooting page, so you can refer to it: https://github.com/hippogamesunity/SimpleAndroidNotificationsPublic/wiki/Troubleshooting

![image](https://user-images.githubusercontent.com/7318172/58532709-030f1e00-81ef-11e9-9a9c-1b313bac5e6c.png)
