### ISSUE TITLE
Error no static method SetNotification

### ISSUE THREAD

**Issue by Wolfaks** [hippogamesunity/SimpleAndroidNotificationsPublic#64]
Hello. I have error in log. Plugin doesn't work.  What i should to do? Thanks you.
E/Unity: AndroidJavaException: java.lang.NoSuchMethodError: no static method with name='SetNotification' signature='(IJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIILjava/lang/String;Ljava/lang/String;ILjava/lang/String;)V' in class Ljava.lang.Object;
    java.lang.NoSuchMethodError: no static method with name='SetNotification' signature='(IJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIILjava/lang/String;Ljava/lang/String;ILjava/lang/String;)V' in class Ljava.lang.Object;

**Comment by GunLengend** [comment]
Same on Unity 2019.3.0f6

**Comment by hippogamesunity** [comment]
Hi! Does it work with a new empty project?

**Comment by breban1** [comment]
Same error here on Galaxy S8, using latest from Unity Asset Store.  No errors on Galaxy S7 (haven't confirmed it they work yet though).

AndroidJavaException: java.lang.NoSuchMethodError: no static method with name "CancelNotification" signature='(I)V" in class Lcom.hippogames.simpleandroidnotifications.Controller:

EDIT: I only receive the error if it is a Gradle build.  Internal doesn't show the runtime error.  Maybe I just don't know what I'm doing lol.

**Comment by hippogamesunity** [comment]
Hi, just visit troubleshooting to fix Gradle setup.
