### ISSUE TITLE
Crash on notification received

### ISSUE THREAD

**Issue by ribusja** [hippogamesunity/SimpleAndroidNotificationsPublic#65]
Hello.
Yesterday our studio published an app with your plugin. Everything was ok in test phase but now some users have crashes with these error:
https://pastebin.com/DcrkxRAF
But i don't sure why those error happened, cause i'm using default icon present in .aar file. Here's my code to schedule simple notification: https://pastebin.com/VgfwP3kb. Can you help me with these problem?

Unity: 2019.1.5f1, latest plugin version, apk created on MacOs.

UPDATE: previously there was an custom icon and sound in notification which was deleted in new update. Can these be a origin for these error?

**Comment by hippogamesunity** [comment]
Hi! MacOs creates hidden meta files that can cause the error. Try to remove and redownload the asset.

**Comment by hippogamesunity** [comment]
I recommend using Windows to change AAR in manual.

**Comment by ribusja** [comment]
In latest release we are using default icon exactly because we cannot modify aar properly. So we published with aar as-is in store plugin.

Also we've tested this error and maybe found why crash happened.

If user schedule notification on previous version (where we have custom sound and icon) with setting custom data, next he update but NOT enter an app to reschedule notification (in update there is no custom icon and sound, also code refers to defaults). After this when notification is ready to fire - all systems just crashed. Also after user reenter an app - notification will not work at all, only app reinstall helps notification to work again.

I suspect that there is no checking for icon existing and plugin just crashes. Am i right about this?

**Comment by ribusja** [comment]
If i've used only previous update or only latest update - all works just fine. All problems happening when notification is scheduled and app updating without entering and playing.

**Comment by hippogamesunity** [comment]
Yes, this may happen. Try to publish an update with missed icon, this will be the fastest solution for you. Use windows to edit AAR. I will add try/catch to my asset in next update.

**Comment by ribusja** [comment]
Ok, I'll try. But there is another question. We have a custom sound in previous version. Can this cause problem also, if i managed to fix icon error? Also in latest release manual I'm not seeing any info about custom sounds. Is there any changes in this and will be previous way work in this update (creating "raw" folder inside "res" folder and placing sound in there)?

**Comment by ribusja** [comment]
Also previously tried to edit aar on windows, but then ingame at notification scheduling error were thrown. 
java.lang.ClassNotFoundException: com.hippogames.simpleandroidnotifications.Controller

I'll try edit aar not with more precision. Hope it help me.

**Comment by ribusja** [comment]
Ok, editing an aar in windows helped. But then another problem happened.
1) Make clear install of an app
2) Schedule notification
3) Upgrading app
4) Do not enter app at all.
After these steps when scheduled time is ended nothing happened. Notification not firing at all (waited 5 mins for these). When after these I reenter app, schedule new notification and waited again to target time - nothing happened also. It seems that plugin not working at all. (Also tried to rewind time for a week ahead - also no notification. In previous versions rewinding worked well).
Is there any possible fix for these?

**Comment by hippogamesunity** [comment]
You are doing something wrong. Start step by step research.
- check empty project with the asset
- add a new icon and check again
- build your project, check it

Also refer to FAQ section about manifests.

чт, 8 авг. 2019 г., 16:51 Anton Rybak <notifications@github.com>:

**Comment by ribusja** [comment]
Tried yesterday plugin in empty projects. Tried different combinations and finded one that corrupt all logic. Created 2 apk with different settings and installing first, scheduling notification, updating to second, forwarding time to trigger notification - waiting for result.
1) Both Unity 2019.1.5, Il2Cpp, net 4.0, arm64/armv7 architecture - works good.
2) Both Unity 2019.1.5, second - with same settings, but first different - mono, armv7, net 3.5 - works good too.
These two works with your last plugin (2.9).
3) First - Unity 2018.1.0f2, Mono, armv7, net 3.5, and plugin version very old (imported in project and  - november 2018, maybe more older version idk), Second - 2019.1.5, same as in 1 variant. 
In last case notification will not work at all. Entering an app and reschedulling didn't help - all plugin brokes and stop working.

**Comment by hippogamesunity** [comment]
Can you provide crash logs? I can confirm that old plugin versions may have bugs (that's why I'm updating it =)

**Comment by ribusja** [comment]
No, there is no crashes after these. Notifications just stopped working. Tried to analyze device logs, but i've only saw, that notification activity starts, but nothing happened.
Now i don't have any possibility to send you logs, i'll try to reproduce it next week and gather all data.

**Comment by hippogamesunity** [comment]
Ok, as I can't reproduce it.
