### ISSUE TITLE
Is Simple Android Notifications plugin working properly in Unity 2019.1.12f1?

### ISSUE THREAD

**Issue by leongkee** [hippogamesunity/SimpleAndroidNotificationsPublic#66]
When I run the **NotificationManager.Cancel( int id )** function on an Android device, it stops at this line:
`JavaClass.CallStatic( "CancelNotification", id );`

Once it stops at that line, it does not process the rest of the code after that line.
Is the plugin able to work properly in Unity 2019.1.12f1?
How could I solve the problem?

Thank you.

**Comment by leongkee** [comment]
I have tried to create a new project with the plugin in Unity 2019.1.12f1.
It works properly in the new project.

I would like to ask, what cause will make it stop at the following line?
`JavaClass.CallStatic( "CancelNotification", id );`

Please advise.
Thank you.

**Comment by hippogamesunity** [comment]
Hi! I'm unable to check the asset on exact version of Unity, but if it works with empty project, I would recommend you to integrate the package as step-by-step.
Do you have any logs? Why do you think it stops at the following line?

**Comment by Mathling** [comment]
> Hi! I'm unable to check the asset on exact version of Unity, but if it works with empty project, I would recommend you to integrate the package as step-by-step.
> Do you have any logs? Why do you think it stops at the following line?

I put Debug.Log() for printing out the log for every line of code to see where it stops at.
Then I found out that there is debug log before `JavaClass.CallStatic( "CancelNotification", id );` but there is no debug log after it.

In the Simple Android Notifications plugin's NotificationManager.cs script:

```
public static void Cancel(int id)
{
           Debug.Log( "NotificationManager: Cancel - id = " + id );
#if UNITY_ANDROID && !UNITY_EDITOR
           Debug.Log( "JavaClass.CallStatic: CancelNotification" );
           JavaClass.CallStatic( "CancelNotification", id );
            Debug.Log( "NotificationIdHandler.RemoveScheduledNotification" );
           NotificationIdHandler.RemoveScheduledNotificaion( id );
           Debug.Log( "NotificationIdHandler.RemoveScheduledNotification Done" );
#endif
           Debug.Log( "NotificationManager: Cancel - Done" );
}
```

**Output:**
NotificationManager: Cancel - id = 5
JavaClass.CallStatic: CancelNotification

**Comment by hippogamesunity** [comment]
Then you need to get logs using adb logcat.

**Comment by leongkee** [comment]
> Hi! I'm unable to check the asset on exact version of Unity, but if it works with empty project, I would recommend you to integrate the package as step-by-step.
> Do you have any logs? Why do you think it stops at the following line?

I put Debug.Log() for printing out the log for every line of code to see where it stops at.
Then I found out that there is debug log before `JavaClass.CallStatic( “CancelNotification”, id );` but there is no debug log after it.

In the Simple Android Notifications plugin’s NotificationManager.cs script:
```
public static void Cancel(int id)
{
          Debug.Log( “NotificationManager: Cancel - id = ” + id );
#if UNITY_ANDROID && !UNITY_EDITOR
          Debug.Log( “JavaClass.CallStatic: CancelNotification” );
          JavaClass.CallStatic( “CancelNotification”, id );
          Debug.Log( “NotificationIdHandler.RemoveScheduledNotification” );
          NotificationIdHandler.RemoveScheduledNotificaion( id );
          Debug.Log( “NotificationIdHandler.RemoveScheduledNotification Done” );
#endif
          Debug.Log( “NotificationManager: Cancel - Done” );
}
```
Output:
NotificationManager: Cancel - id = 5
JavaClass.CallStatic: CancelNotification

**Comment by leongkee** [comment]
> Then you need to get logs using adb logcat.

I printed out the logs using this command and also could not see there was any error-like log after the line of code.

**Comment by leongkee** [comment]
What will happen if I cancel the notification with the ID that has not yet been created?

**Comment by hippogamesunity** [comment]
I'm not sure what will happen if wrong requestCode passed. But if it crashes, you should see this in logs.
![image](https://user-images.githubusercontent.com/7318172/62928249-dcf62480-bdc0-11e9-9bb8-e1ad3a02de11.png)

![image](https://user-images.githubusercontent.com/7318172/62927940-33af2e80-bdc0-11e9-9b9c-b394f412ca7e.png)
https://developer.android.com/reference/android/app/PendingIntent.html#getBroadcast(android.content.Context,%20int,%20android.content.Intent,%20int)

Finding the answer can take time, but you can use CancelAll() to cancell all and NotificationIdHandler to manage IDs.

I will check this task when I have a free time
https://github.com/hippogamesunity/SimpleAndroidNotificationsPublic/issues/67

**Comment by leongkee** [comment]
I have tested in a new project to cancel the notification with any random ID that has not yet been created, and it can still work properly without any crashing or stopping at the line of `JavaClass.CallStatic("CancelNotification", id);`.

Not sure why it does not work in the existing project.

**Comment by leongkee** [comment]
I have tried putting **NotificationManager.Cancel( int id )** function between each line of code and found out the following cases:

```
Task fetchTask = FirebaseRemoteConfig.FetchAsync();
Assets.SimpleAndroidNotifications.NotificationManager.Cancel( 5 );

fetchTask.ContinueWith( ( task ) =>
{
//  Assets.SimpleAndroidNotifications.NotificationManager.Cancel( 6 );

    if (task.IsCompleted == true && FirebaseRemoteConfig.Info.LastFetchStatus == LastFetchStatus.Success)
    {
        Assets.SimpleAndroidNotifications.NotificationManager.Cancel( 7 );

        FirebaseRemoteConfig.ActivateFetched();
```

At the line of `Assets.SimpleAndroidNotifications.NotificationManager.Cancel( 6 );`, the app crashes on an Android device. So I have commented out the line to let it proceed.

At the line of `Assets.SimpleAndroidNotifications.NotificationManager.Cancel( 7 );`, the Cancel() function stops at the line of `JavaClass.CallStatic("CancelNotification", id);` without any crashing and error.

We are using **FirebaseRemoteConfig** service to fetch the parameter values from the Firebase Remote Config server for updating the local notification settings.

It seems that the **JavaClass.CallStatic()** function cannot work together with **Task.ContinueWith()** function. How can I solve this?

Please advise.
Thank you.

**Comment by hippogamesunity** [comment]
I'm not familiar with Firebase. I only know it has push notifications, so there is a chance it can conflict with my asset as they both use AlarmManager and other Android services.

**Comment by leongkee** [comment]
Could I change my Android phone's local time to test the local notification?

Because I noticed that if the local notification was scheduled at 5 seconds later, it did show up. But if it was scheduled at 1 day later, and I changed my phone's local time to yesterday (1 day before), the local notification did not show up.

**Comment by hippogamesunity** [comment]
My asset is just a wrapper over native android notification system. I would recommend you to refer to Google docs for this question. You can start from https://developer.android.com/reference/android/app/AlarmManager
![image](https://user-images.githubusercontent.com/7318172/63926420-7b86b480-ca54-11e9-8f2b-dc6e9852134e.png)

**Comment by leongkee** [comment]
The local notification system seems like not working if I kill the app.

After a local notification has been scheduled, if the app is in the background, then the local notification message will show up. But if I kill the app, then it does not show up.

Is this the normal behaviour?

**Comment by hippogamesunity** [comment]
This may be affected by energy saving features as described in FAQ.

**Comment by leongkee** [comment]
> Could I change my Android phone's local time to test the local notification?
> 
> Because I noticed that if the local notification was scheduled at 5 seconds later, it did show up. But if it was scheduled at 1 day later, and I changed my phone's local time to yesterday (1 day before), the local notification did not show up.

Sorry that I tested wrongly for this, I should change my phone's local time to tomorrow (1 day later) instead. So, I am actually able to test the local notification system by changing my phone's local time. Sorry for the confusion.

**Comment by leongkee** [comment]
> This may be affected by energy saving features as described in FAQ.

Do I need to add `android.permission.RECEIVE_BOOT_COMPLETED` into the Android Manifest file to make the local notification system work even after the app is killed?

**Will notifications work after device reboot?**
Basically Android erases all local notifications on reboot (as they are scheduled alarms). Paid plugin version recreates all scheduled notifications after reboot, that’s why it requires android.permission.RECEIVE_BOOT_COMPLETED permission.

**Comment by hippogamesunity** [comment]
RECEIVE_BOOT_COMPLETED is required for reboot.

**Comment by hippogamesunity** [comment]
Checked with Unity 2019.2.6, it's works fine.
