### ISSUE TITLE
Night Mode

### ISSUE THREAD

**Issue by Ravenh0lm** [hippogamesunity/SimpleAndroidNotificationsPublic#68]
Hi, I am trying to implement night mode in order to receive notifications without sound by using
ScheduleCustom() method with setting
**notificationParams** fields to
        ...........
	**Sound = false,
	Vibrate = false,
	Light = false**
        ...........

On Android 5.0.1 all works fine, messages without sound, but on Android 9 sound is present.
Please, tell me the right way to solve issue.
All reproduce in empty Unity project and DemoScene.

**Comment by hippogamesunity** [comment]
Hi! Refer to FAQ on wiki. You need the section about changing notification settings. Basically you need to create 2 channels - day/night.

**Comment by Ravenh0lm** [comment]
Thanks for fast reply.
The first call creates a channel with the specified parameters?
I modify **ScheduleWithChannel ()** method like this:
......
                Id = NotificationIdHandler.GetNotificationId(),
                Delay = TimeSpan.FromSeconds(5),
                Title = "Notification with news channel",
                Message = "Check the channel in your app settings!",
                Ticker = "Notification with news channel",
                **ChannelId = channelId,
                Vibrate = day, // true/false
                Light = day, // true/false
                Sound = day, // true/false**
                ExecuteMode = NotificationExecuteMode.ExactAndAllowWhileIdle,
                Importance = NotificationImportance.Max,
                **ChannelName = channelName**
......

In notification settings i see two created channels.
Vibrate workin as expected (in channel "Night" - off, "Day" - on), but sound is steel there, in both channels.
How correctly create muted and normal channels?

**Comment by hippogamesunity** [comment]
Does Sound setting work in empty project with clean plugin setup?

чт, 12 сент. 2019 г., 0:40 Ravenh0lm <notifications@github.com>:

**Comment by Ravenh0lm** [comment]
I use empty Unity 2019.1.10f1 project, clean plugin and included DemoScene.
Send message with button "With channel in 5s (API 26+)" just changing property Sound = false/true
Android 9 Sound always ON. Correctly only Vibrate (true/false).
Android 5 all settings work fine.

**Comment by hippogamesunity** [comment]
Good, I will check this setup.

**Comment by hippogamesunity** [comment]
Hi! I was able to test the asset both on Android 8 & 9. My scenario:
- create an empty project with Unity 2019.2.6 & import the plugin
- set Sound = false
- build and launch a notification (result: no sound)
- open app settigns/notifications (result: sound toggle is OFF)

**Comment by Ravenh0lm** [comment]
Hi, sorry, but not workin on my device.
Unity 2019.2.6, download clean plugin from store, add only one string
Here is code:
```
public void ScheduleWithChannel()
{
     var notificationParams = new NotificationParams
     {
          Id = NotificationIdHandler.GetNotificationId(),
          Delay = TimeSpan.FromSeconds(5),
          Title = "Notification with news channel",
          Message = "Check the channel in your app settings!",
          Ticker = "Notification with news channel",
          Sound = false,
          ChannelId = "com.company.app.news",
          ChannelName = "News"
     };
     NotificationManager.SendCustom(notificationParams);			
}
```
May be wrong place to set sound false?
Can you share me apk? I test on my device.

**Comment by hippogamesunity** [comment]
Hm, I was testing without a channel. Sure, I will share it soon.

**Comment by hippogamesunity** [comment]
I've made a research and found this link: https://www.reddit.com/r/Xiaomi/comments/906p09/notification_sounds_not_working_on_miui_10_8719/
Also I've updated FAQ:
![image](https://user-images.githubusercontent.com/7318172/68185396-7f820600-ffb2-11e9-9665-78787cbfea7b.png)

**Comment by Ravenh0lm** [comment]
Hi, again) I made it.
Importance = NotificationImportance.Low - on Android 5 with vibrate, but full silence on 9 +
Importance = NotificationImportance.Min - on Android 5, 7 , 10 it is goal.
