### ISSUE TITLE
No static method with a name "Cancel all notifications"

### ISSUE THREAD

**Issue by KasparasK** [hippogamesunity/SimpleAndroidNotificationsPublic#70]
![unknown](https://user-images.githubusercontent.com/22654917/64950447-0accfe00-d884-11e9-8d2e-52d1b46034b2.png)

Get this every time when launching the app
Tested on Android 9

**Comment by hippogamesunity** [comment]
1. Update the plugin.
2. Check it with a new demo project.

**Comment by KasparasK** [comment]
Deleted old files, re-imported from store, built demo scene, same error when canceling all

**Comment by hippogamesunity** [comment]
Please attach your demo (Google Drive maybe) and provide software details.

**Comment by hippogamesunity** [comment]
Also check if ProGuard and code minimizer were disabled.
https://github.com/hippogamesunity/SimpleAndroidNotificationsPublic/wiki/Troubleshooting

**Comment by KasparasK** [comment]
ok, so I did this 
![image](https://user-images.githubusercontent.com/22654917/64980676-0247e800-d8c3-11e9-926f-a9d8e6576b4b.png)

And the error is gone, but is ok to leave minify on none? Are there any downsides to that?

**Comment by hippogamesunity** [comment]
That's how it works. You can try to setup ProGuard as in FAQ.

пн, 16 сент. 2019 г. в 20:46, KasparasK <notifications@github.com>:

**Comment by KasparasK** [comment]
The instructions are quite wage, is my setup correct?
![image](https://user-images.githubusercontent.com/22654917/65059595-f3bf0680-d97e-11e9-9f41-926c40f6b826.png)
I need to use both gradle template and proguard file?

**Comment by hippogamesunity** [comment]
Disable Proguard or use the workaround from FAQ.

**Comment by KasparasK** [comment]
Yes i'm trying to use the workaround, so i'm interested if my setup for using workaround is correct. I added the line into proguard-user

**Comment by hippogamesunity** [comment]
I'm not an expert in Proguard and I don't use it. You could refer to
Proguard docs. All I know is Proguard can delete "unused" java libs.

вт, 17 сент. 2019 г. в 19:17, KasparasK <notifications@github.com>:

**Comment by KasparasK** [comment]
Yeah, thats what I what I found out, still as far as I understand its recomended to use, and my setup seems to be working, so thanks for your help !
