### ISSUE TITLE
How to not receive notifications then application running?

### ISSUE THREAD

**Issue by andreyshade** [hippogamesunity/SimpleAndroidNotificationsPublic#72]
How to not receive notifications then application running?

**Comment by hippogamesunity** [comment]
CancellAll on Start

**Comment by andreyshade** [comment]
Thanks for your answer, but I schedule a lot of notifications with different delays. How don't receive notification during game session?

**Comment by hippogamesunity** [comment]
You can only cancel them, there is no another way.

пн, 18 нояб. 2019 г. в 23:29, Andrii Lytvynenko <notifications@github.com>:
