### ISSUE TITLE
Notifications don't load after closing app in background

### ISSUE THREAD

**Issue by YotamEdge226** [hippogamesunity/SimpleAndroidNotificationsPublic#74]
The notifications don't load after I close the app in the background. After I reopen the app the notifications show.

How can I make the notifications load after I close the app in the background?

Using Galaxy 10 without root enabled. Power saving is off. I get notifications from games I install.

**Comment by hippogamesunity** [comment]
Hello! Hope this link will help you!
https://github.com/hippogamesunity/SimpleAndroidNotificationsPublic/wiki/Troubleshooting


ср, 5 февр. 2020 г. в 14:35, YotamEdge226 <notifications@github.com>:

**Comment by YotamEdge226** [comment]
It works when I create a new project but not in my existing project. Any idea what I can do?

**Comment by hippogamesunity** [comment]
It may be manifest issue or conflicts with other plugins like Firebase.

**Comment by YotamEdge226** [comment]
Does your plugin not work when Firebase is integrated?

**Comment by hippogamesunity** [comment]
I don't know because I'm not familiar with it, but there were some reports about Firebase. At first I would check manifests.

**Comment by hippogamesunity** [comment]
https://github.com/hippogamesunity/SimpleAndroidNotificationsPublic/issues/73

**Comment by hippogamesunity** [comment]
https://github.com/hippogamesunity/SimpleAndroidNotificationsPublic/issues/66
