### ISSUE TITLE
Custom sound and light

### ISSUE THREAD

**Issue by Hayke69** [hippogamesunity/SimpleAndroidNotificationsPublic#75]
Hello, 

I encounter some problems to customize notification's sound effect. 
 Following the instruction shown in the manual, the system doesn't recognize it. Is my structure wrong ?   https://drive.google.com/drive/folders/1SFdp3ItfL0B1RFUZEhKYaQ_56K5hCXYD

Same problems with light. What this feature is pretend to do ? (the structure of the code is present on the url link == picture).

Thanks,

**Comment by hippogamesunity** [comment]
Hi! I've checked your AAR and it works with this custom DING. At first check the app Notification Settings, make sure that Notifications are enabled and Notification Sounds are enabled (this may be disabled by default by some vendors). Also refer to section "Can't change notification settings on Android 8 and later (sound, vibration, lighting)" of this Page
https://github.com/hippogamesunity/SimpleAndroidNotificationsPublic/wiki/Troubleshooting

**Comment by hippogamesunity** [comment]
And about custom Light - make sure that your device supports LED notifications.

**Comment by Hayke69** [comment]
Hello, 

I've seen the parameters of my phone in "display" and they are no option called "led notification". So I think my phone is not configure with this type of things. I've an Android 7. 

For the sound, I've only change the "beep" (edit his name) and it's works (for all sounds). 

Is it possible to change the LargeIcon ?

**Comment by hippogamesunity** [comment]
No, LargeIcon can be only as the app icon.
