### ISSUE TITLE
issue with canceling all notifications

### ISSUE THREAD

**Issue by jamesbe** [hippogamesunity/SimpleAndroidNotificationsPublic#76]
Hi, I had my application working for sometime with this great plugin! But recently I went to update it and now when I try and compile and run it I seem to be getting this error when I run it in the abd logcat. Do you have an suggestions on how to fix this?

![android_notification_error](https://user-images.githubusercontent.com/12224628/76480439-09206500-63e5-11ea-902e-d403a885ce11.PNG)

**Comment by jamesbe** [comment]
Actually this seems to happen with any call I make with your plugin's API calls. For example, I tried to just set a custom notification and I got the attached image in my logs as well. I am running Unity 2019.3.4f1.
![set_notification_error](https://user-images.githubusercontent.com/12224628/76483419-5e607480-63ed-11ea-9a70-d7822a8112a7.PNG)

**Comment by hippogamesunity** [comment]
Hi! Looks like the code was deleted by ProGuard, refer to FAQ for more info.

чт, 12 мар. 2020 г., 6:09 jamesbe <notifications@github.com>:

**Comment by jamesbe** [comment]
Yup that was it, thanks!
