### ISSUE TITLE
How to schedule a notification to a fixed time?

### ISSUE THREAD

**Issue by EcoEditor** [hippogamesunity/SimpleAndroidNotificationsPublic#77]
Hi! 
I'm using your asset to schedule notifications in unity app and after following [this tutorial](https://www.youtube.com/watch?v=ZIdxnvo8PYM), I've learned how to schedule a notification after 30 sec, since the app is paused.

My goal is to have 3 types of notifications, regardless the status of the application (paused or not): 
1. Once a day at 20:00
2. Once a week at Thursday at 20:00
3. Once a month, on last day of month at 20:00 

Currently I'm struggling at having a repeated notification, each day at 20:00

Your code use TimeSpan, how can I set the TimeSpan to 20:00 each day? 
Do you have any tutorials you can recommend for that?

Thank you

**Comment by hippogamesunity** [comment]
Hi! Use NotificationParams.Delay to set a delay to desired time. Simply calculate it.
Then specify NotificationParams.RepeatInterval and set NotificationParams.Repeat = true.

**Comment by EcoEditor** [comment]
Hi @hippogamesunity , is this option open to the free version? 
The code doesn't give me this option...

![image](https://user-images.githubusercontent.com/42212240/79358270-a96c2b00-7f49-11ea-9d25-b45ab6f611fc.png)

**Comment by hippogamesunity** [comment]
You should create an instance of that class. Refer to examples.
