### ISSUE TITLE
clicked the grouped notification can open app, but clicked the item/single notification can't open.

### ISSUE THREAD

**Issue by abiaocom** [hippogamesunity/SimpleAndroidNotificationsPublic#80]
hi, developer:
i clicked the grouped notifications can open app, but clicked the item/single notification can't open.
when clicked grouped notifications not closed, 
and when clicked item/single notification can't open app, item notification closed.
i test devices: samsung SM-G928V Android 7.0, API 24

**Comment by hippogamesunity** [comment]
Tested on Android 12, it works no matter where you click.
