### ISSUE TITLE
Notifications are not working. Built for Android with Unity 2019.4.12f1

### ISSUE THREAD

**Issue by VusalJalilov** [hippogamesunity/SimpleAndroidNotificationsPublic#81]
Confirmed step-by-step each bullet point in the troubleshooting section:

1) Brand new project in **Unity 2019.4.12f1** with clean install of the latest version of SimpleAndroidNotifications from the AssetStore.
2) Built .apk file from the DemoScene
3) Installed and tested on Samsung Note 10, Android 10, One UI version 2.5, Notifications are enabled, Energy Saving is disabled - **Notifications are not working**
4) Installed and tested on Xiami Redmi 6A, Android 9, Notifications are enabled, Energy Saving is disabled - **Notifications are not working**
5) As advised regarding "set code Minimizer to None from Build Settings":
In Unity 2019.4.12f1, Player Settings -> Optimization -> Managed Stripping Level - Low (which is Default and there is no "None") - **Notifications are not working**
6) Built with "Strip Engine Code" checkbox both checked and unchecked - **Notifications are not working**
7) Not using Gradle minimizer

Did a clean install in Unity **2017.4.39f1** - **Notifications are working perfectly fine.**

*Noted that the "Launched from notification" checkbox is disabled in both builds.

**Comment by hippogamesunity** [comment]
Hello! I can confirm that notifications work in 2019 and 2020 (in my own games and apps). Also there are no similar reports (emails, reviews). There should be something with your setup. Anyway, I'll check this soon, thanks.

**Comment by VusalJalilov** [comment]
Thank you for your response.
What version of 2019.4 have you tested?

*I have a paid version of SimpleAndroidNotifications.

**Comment by VusalJalilov** [comment]
UPDATE:
Did a brand new clean installation of Unity 2019.4.15f1 using Unity HUB 2.4.2 with recommended Android SDK & NDK and OpenJDK.
Imported SimpleAndroidNotifications from the Asset Store. Followed the Troubleshooting guide once again. 
Notifications are STILL not working :(

**Comment by hippogamesunity** [comment]
![Uploading Screenshot_2020-11-21-13-21-23-243_com.SimpleAndroidNotifications.png…]()

**Comment by hippogamesunity** [comment]
Hello! I've just tested it on Unity 2020.1.11 with default settings (Mono, NET 2.0). It works on MiPad 4. Unfortunately, I don't have Android 10 device yet.
![image](https://user-images.githubusercontent.com/7318172/99874987-01b08d00-2bfd-11eb-85dd-d8058ca8b795.png)

**Comment by VusalJalilov** [comment]
Hello and thank you for your response!

Could you please test it on 2019.4.15f1?

I will download 2020 and test as well.

Regards,
Vusal

**Comment by VusalJalilov** [comment]
Note that 2020.1.11 is NOT LTS.

**Comment by VusalJalilov** [comment]
I am building with IL2CCP with ARM64 support using Gradle.

**Comment by VusalJalilov** [comment]
Tried with Mono on Unity 2019.4.15f1 - Notifications are STILL not working

**Comment by hippogamesunity** [comment]
Can you try another device? Not Android 10.

сб, 21 нояб. 2020 г. в 16:38, VusalJalilov <notifications@github.com>:

**Comment by VusalJalilov** [comment]
Installed and tested on Samsung Note 10, Android 10, One UI version 2.5, Notifications are enabled, Energy Saving is disabled - Notifications are not working

Installed and tested on Xiami Redmi 6A, Android 9, Notifications are enabled, Energy Saving is disabled - Notifications are not working

**Comment by VusalJalilov** [comment]
UPDATE!
Things are getting even worse. I have re-installed 2017 and 2019 once again.
Now my builds on both Unity version does not show Notifications. 

Clean project, nothing else but SimpleAndroidNotifications's Demo Scene.

If i send you my .apk files will you be able to compare it to your builds on 2017 and 2019?

**Comment by hippogamesunity** [comment]
I can test your APK on my device, yes, share it.

вс, 22 нояб. 2020 г. в 18:48, VusalJalilov <notifications@github.com>:

**Comment by VusalJalilov** [comment]
UPDATE! Problem resolved!

I was using "Gradle" in Release and Debug in Player Settings->Minify...
