### ISSUE TITLE
Notification doesn't work properly when app is closed 

### ISSUE THREAD

**Issue by FlowOfRemi** [hippogamesunity/SimpleAndroidNotificationsPublic#82]
I just tested with DemoScene. If app is running all notification options works fine but not when app is closed.(Not in background , absolutely closed my app)
For example, I click Simple in 120s button then close my app, It doesn't load any notification after 120s and over, but load notification directly when start my app like doing homework.

**Comment by hippogamesunity** [comment]
Hello! Did you check FAQ and test on other devices?
