### ISSUE TITLE
Can't work with Firebase Analytics

### ISSUE THREAD

**Issue by phamhphuc** [hippogamesunity/SimpleAndroidNotificationsPublic#85]
3 days ago I add latest version firebase analytics to my games and the game can't push notification after specific time. I tried to test with 5 minutes and didn't see as before adding firebase analytics.

I read FAQ and try to use this 

Importance = NotificationImportance.Max

But after build and try again and it doesn't work again.

Can you tell me more detail about where and how to try with way to make it work?

Thanks,
Phuc

**Comment by phamhphuc** [comment]
Finally found the problem, just need to set Minify in player settings to None then everything will be fine

**Comment by stevekim0417** [comment]
Thank you so much. It works.

**Comment by hippogamesunity** [comment]
https://github.com/hippogamesunity/SimpleAndroidNotificationsPublic/wiki/Troubleshooting

Try Gradle section.
