### ISSUE TITLE
Android 12 and Google Play Store incompatibility issue

### ISSUE THREAD

**Issue by rthery** [hippogamesunity/SimpleAndroidNotificationsPublic#88]
Hello

Even though the version 3.0 on the store is labeled as Android 12 compatible, there is a remaining issue.

The simple-android-notifications.aar has following receiver defined in its AndroidManifest.xml:
```
<receiver android:name="com.hippogames.simpleandroidnotifications.RebootManager">
  <intent-filter>
    <action android:name="android.intent.action.BOOT_COMPLETED" />
  </intent-filter>
</receiver>
```

Which is missing android:exported, as explained here:
https://developer.android.com/about/versions/12/behavior-changes-12#exported

Any build uploaded to the Google Play Console targeting Android 12+ with this .aar will be rejected because of this.

As a temporary solution, I edited the file in the .aar, but I'd rather not having to maintain my own fork of this asset.

**Comment by hippogamesunity** [comment]
Hello, sorry for the delay, I'll check this. BTW you can fix this by yourself by modifying the manifest inside simple-android-notifications.aar

**Comment by hippogamesunity** [comment]
Am I right it should be like this?
![image](https://user-images.githubusercontent.com/7318172/168237158-382269c5-b173-415d-9cf9-862307151813.png)

**Comment by rthery** [comment]
Yes that's indeed what I did and it allowed me to upload my build to the Google Play Store :)

**Comment by hippogamesunity** [comment]
Update 3.1 is on review.
