### ISSUE TITLE
Notification not received after restart

### ISSUE THREAD

**Issue by ManaliKanungo** [hippogamesunity/SimpleAndroidNotificationsPublic#91]
I bought the asset today as I wanted the notification after restart feature. I am unable to receive the notification after restarting.
I checked the manifest file and the required permissions are mentioned in it.

Please help me in getting this resolved.

**Comment by hippogamesunity** [comment]
Hi! I've downloaded the laters asset version and made Build&Run it on Galaxy Tabs S6 Lite. Ufter pressing the test button, a notification has appeared after device reboot.

I can suggest you to check device logs (adb logcat).

**Comment by ManaliKanungo** [comment]
I understand that there might be some settings required at my end. Can you please help me with it.
I see no errors in the logcat.

**Comment by hippogamesunity** [comment]
How can I help you? It works for me and other customers. You can also request a refund from the asset store.
