### ISSUE TITLE
Notifications not working on Android 11

### ISSUE THREAD

**Issue by SMahdiFaghih** [hippogamesunity/SimpleAndroidNotificationsPublic#92]
Hi. After changing the app's Target API from 30 to 31 I had an issue getting notifications on Android 12. After getting the new release from Asset Store and updating the .aar file, that issue was fixed but now notifications don't work on Android 11. They are fine on some other versions like Android 9 and 12 that I tested.

Please help me in getting this resolved.

**Comment by hippogamesunity** [comment]
Hello! I'll test in on my Android 11 device and let you know.
As it works with Android 9, I think it's not an API issue and most likely relates to your device.

**Comment by SMahdiFaghih** [comment]
Thanks for your quick response! I actually tested it on 2 of my friends' phones with Android 11 and it didn't work on any of them so I thought that it was probably not related to the device.

**Comment by hippogamesunity** [comment]
Hi! At the moment I can only confirm the demo also doesn't work on my device with Android 11.
I can't find anything in logs.
I'va also tried to run old asset versions with no luck, so I can suggest that this may relate to Unity settings.
The only clue is that I have a few games with this asset that show notifications on the same device.
Thus, I need more time for investigation and finding environment differences with these project.

**Comment by hippogamesunity** [comment]
I've added logs to make sure that all funcs are called in Java.

Basically it should look like:
1) SimpleNotifications: SetNotification() invoked.
2) SimpleNotifications: AlarmManager.set() invoked.
3) NotificationManager.notify() invoked.

The last one is not invoked. So, AlarmManager is set, but after delay there is no notification fired for some reason, with no errors and additional logs. Unfortunately, my device is run under Xiaomi MIUI, it's not clear Android.

What devices with Android 11 do you have?

[simple-android-notifications.zip](https://github.com/hippogamesunity/SimpleAndroidNotificationsPublic/files/10169282/simple-android-notifications.zip)

**Comment by hippogamesunity** [comment]
As mentioned here https://www.androidcentral.com/how-fix-miui-push-notifications
Push notifications continue to be a significant problem in MIUI thanks to Xiaomi's aggressive memory management.

**Comment by hippogamesunity** [comment]
Right, I've made both workarounds, the first didn't work, but the second (Battery & performance) made the trick. So now notifications are shown on Android 11 (MIUI).

You can check similar articles for your shells and use the AAR attached to check ADB los.

**Comment by SMahdiFaghih** [comment]
Hi. Both of those devices were Xiaomi too. On one of them, the notifications now work correctly but on the other one, there is still no notification. Well, it seems that it's more about Xiaomi devices and I hope it works fine on Samsung devices which most of our users are probably using. 
Thanks for your quick response and effort in investigating this issue. I'll close this issue now.
