### ISSUE TITLE
How to give permission in Android 13?

### ISSUE THREAD

**Issue by myohyun** [hippogamesunity/SimpleAndroidNotificationsPublic#93]
Starting with Android 13, to send notifications, you must first grant permission for notifications. Is there a way to only open a window that allows notification permission without sending notifications in Android 13 or higher? When a window is opened by sending a notification, the notification is simply called in Android 13 or lower.

**Comment by hippogamesunity** [comment]
Hi, please refer to https://docs.unity3d.com/Manual/android-RequestingPermissions.html
